In [6]:
import gym
import numpy as np
import time
import random

In [7]:
env = gym.make('FrozenLake-v1', render_mode='ansi')

In [8]:
action_space_size = env.action_space.n
observation_state_size = env.observation_space.n

Q_table = np.zeros((observation_state_size,action_space_size))
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
num_episodes = 20000
max_steps_per_episode = 400

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [12]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()[0]
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        exploraiton_rate_threshold = random.uniform(0,1)
        if exploraiton_rate_threshold > exploration_rate:
            action = np.argmax(Q_table[state,:])
        else:
            action = env.action_space.sample()
        new_state,reward,done,truncated,info = env.step(action)
        Q_table[state, action] = Q_table[state, action]*(1-learning_rate) + learning_rate * (reward + discount_rate * np.max(Q_table[new_state,:]))
        state = new_state
        rewards_current_episode += reward

        if done:
            break

    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)

In [13]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000


********Average reward per thousand episodes********

1000 :  0.05200000000000004
2000 :  0.20700000000000016
3000 :  0.45300000000000035
4000 :  0.5840000000000004
5000 :  0.7220000000000005
6000 :  0.7520000000000006
7000 :  0.7400000000000005
8000 :  0.7450000000000006
9000 :  0.7610000000000006
10000 :  0.7700000000000006
11000 :  0.7850000000000006
12000 :  0.7470000000000006
13000 :  0.7820000000000006
14000 :  0.7450000000000006
15000 :  0.7550000000000006
16000 :  0.7430000000000005
17000 :  0.7530000000000006
18000 :  0.7490000000000006
19000 :  0.7680000000000006
20000 :  0.7620000000000006
